autonomio/talos

talos/model/normalizers.py
talos/reporting.py
talos/scan.py

Add documentation to the `Scan` and `Reporting` classes, and `lr_normalizer` function.
Additionally, cleanup a bit, make sure no lines go over 80 characters, etc.

Merge doc into master (add some doc strings)

---

talos/metrics/keras_metrics.py
talos/metrics/names.py
talos/metrics/performance.py
talos/metrics/score_model.py
talos/model/examples.py
talos/model/ingest_model.py
talos/model/layers.py
talos/model/shapes.py
talos/parameters/round_params.py
talos/reducers/sample_reducer.py
talos/utils/results.py

- make sure that all tests are passed 
- create some unit tests and update testing procedures accordingly 
- make PR to dev (or daily-dev)

fixes #62 and adds several missing docstrings

---

talos/metrics/performance.py

Issue with fn and fp values

---

README.md
examples/A Very Short Introduction to Hyperparameter Optimization of Keras Models with Talos.ipynb

- changed the README.md links for example notebooks
- cleaned up output cells from one notebook

small change in README.md and example notebooks

---

talos/utils/results.py

Issue with taking the minimum value

Issue with taking the minimum value

---

.travis.yml
setup.py
talos/__init__.py
talos/parameters/ParamGrid.py

This fixes #135. See [commit details](https://github.com/autonomio/talos/commit/b9e6500ee989ade11185eae8fe871942c87b81f9) for more info on the fix.

weekly daily-dev to dev merge

---

.travis.yml
requirements.txt
setup.py
talos/__init__.py
talos/commands/autom8.py
talos/commands/evaluate.py
talos/commands/reporting.py
talos/reducers/sample_reducer.py
talos/scan/scan_addon.py
talos/scan/scan_finish.py
talos/utils/connection_check.py
talos/utils/exceptions.py
talos/utils/generator.py
talos/utils/validation_split.py

This is a major feature update together with some fixes. Check commit details for more infos.

v.0.4.5 to v.0.4.6 merge

---

README.md
talos/commands/autom8.py
talos/scan/scan_addon.py
talos/scan/scan_finish.py

- Added docstrings to Autom8
- Changed several related instances to bound methods
- Some other small fixes

Some additions and cleanups to v.0.4.6

---

README.md
talos/commands/autom8.py
talos/scan/scan_addon.py

More updates to be included in v.0.4.6

---

README.md
setup.py
talos/__init__.py
talos/scan/scan_run.py
talos/utils/string_cols_to_numeric.py

See commit details for more information.

v.0.4.8 to dev

---

talos/parameters/ParamGrid.py
talos/reducers/sample_reducer.py
talos/scan/scan_run.py

There are some outstanding issues regarding shuffle and stratified that needs to be tested, otherwise seems to work. More testing is of cource prudent

Modify ParamGrid to compute only the part of the grid in the selected downsample

---

talos/scan/Scan.py
talos/scan/scan_prepare.py

Fixes https://github.com/autonomio/talos/issues/222

Allow direct setting of experiment_name

---

README.md
docs/Custom_Reducers.md
docs/Gamify.md
docs/Local_Strategy.md
docs/Optimization_Strategies.md
docs/_coverpage.md
docs/_sidebar.md
docs/index.html
talos/reducers/local_strategy.py
talos/utils/gpu_utils.py

This update is focused on making sure that the docs are up-to-date with the latest changes before deploying >=0.6 to pypi.

(Updated) v0.6.3 to Dev

---

docs/Analyze.md

- make sure that all tests are passed 
- create some unit tests and update testing procedures accordingly 
- make PR to dev (or daily-dev)

The docs for `Analyze` said `plot_bars` for `plot_kde` as well.

---

.github/PULL_REQUEST_TEMPLATE.md
docs/AutoParams.md
docs/Examples_Typical.md
docs/Examples_Typical_Code.md
docs/_coverpage.md
docs/index.html
talos/autom8/autoparams.py

v.0.6.4 to Dev

---

.github/workflows/greetings.yml

- added greetings for first pr
- added greetings for first issue
<hr>

added greetings

---

README.md

removed daily-dev reference

---

test/commands/test_analyze.py
test_local.sh

small fixes

---

.travis.yml
talos/model/output_layer.py
talos/reducers/sample_reducer.py
talos/templates/pipelines.py
test/commands/test_autom8.py
test/commands/test_random_methods.py
test/commands/test_templates.py
test_script.py

Add more tests

---

.github/workflows/ci.yml

This commit actually adds coveralls to ci.yml

---

talos/scan/scan_addon.py

Removes hardcoded values from func_evaluate

---

docs/Examples_PyTorch.md
docs/Examples_PyTorch_Code.md
docs/Examples_Typical_Code.md
docs/_sidebar.md
talos/utils/__init__.py
talos/utils/rescale_meanzero.py
talos/utils/torch_history.py
test/commands/test_rest.py

Ta 406 add full support for hyperparameter optimization with pytorch

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support-request.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
docs/Hidden_Layers.md
examples/iris.py
talos/model/hidden_layers.py
talos/scan/Scan.py

Clean up codacy issues

---

docs/Examples_PyTorch.md
docs/Examples_PyTorch_Code.md

fixed the PyTorch examples for hyperparameter search

---

talos/model/hidden_layers.py
talos/model/network_shape.py
talos/utils/test_utils.py
test/commands/test_rest.py

Adds test utils py

---

talos/utils/power_draw_callback.py

added a callback for monitoring power draw on GPU

---

talos/utils/__init__.py
talos/utils/power_draw_append.py
talos/utils/power_draw_callback.py

Add measure for gpu power draw

---

examples/Recover Best Models from Experiment Log.ipynb
talos/commands/evaluate.py
talos/model/hidden_layers.py
talos/utils/__init__.py
talos/utils/recover_best_model.py

removed debugging print statement in hidden_layers.py

---

examples/Recover Best Models from Experiment Log.ipynb
talos/commands/evaluate.py
talos/model/hidden_layers.py
talos/utils/__init__.py
talos/utils/recover_best_model.py

Remove print from hidden layers

---

.github/workflows/ci.yml

CI Cleanup

---

setup.py

change tensorflow package version

---

setup.py

locks wrangle version to >=0.6.7

---

examples/Recover Best Models from Experiment Log.ipynb

fixed recover best model example notebook

---

talos/__init__.py

Fixes the issue with wrong version marking

---

docs/Restore.md

Delete å character in the wild

Delete unexpected random character

---

talos/autom8/automodel.py
talos/templates/models.py
test-ci.py
tests/commands/recover_best_model.py
tests/commands/test_latest.py
tests/commands/test_scan.py

Fix TF input format

---

README.md

Updated README.md to v1.0

---

setup.py
talos/commands/analyze.py
talos/templates/datasets.py

549 remove heatmap mask

---

setup.py
talos/__init__.py
talos/utils/recover_best_model.py
tests/commands/recover_best_model.py

fixes recovery issue mentioned in #534

---

talos/commands/predict.py
tests/commands/test_latest.py

Fix predict

---

setup.py
talos/parameters/DistributeParamSpace.py
talos/parameters/ParamSpace.py
tests/commands/test_latest.py

Improve param space

---

docs/Examples_Typical.md

fixed tuple input reference from 'step' to 'n'

---

docs/_coverpage.md

updated docs version

---

.github/PULL_REQUEST_TEMPLATE.md

improved PR template

---

docs/Scan.md
setup.py
talos/parameters/DistributeParamSpace.py
talos/scan/scan_prepare.py
tests/commands/test_latest.py

Scan allows ParamSpace as input

---

talos/distribute/DistributeScan.py
talos/distribute/distribute_utils.py

bug fix for writing model to script

---

setup.py
talos/__init__.py
talos/parameters/ParamSpace.py

Fix param index

---

docs/Energy_Draw.md
docs/_coverpage.md
docs/index.html
setup.py
talos/__init__.py
talos/utils/power_draw_append.py

Fix powerdraw callback

---

.github/PULL_REQUEST_TEMPLATE.md
docs/_coverpage.md
docs/index.html
setup.py
talos/__init__.py
talos/parameters/DistributeParamSpace.py
talos/scan/scan_prepare.py
talos/utils/test_utils.py

Fix distributedparams

---

docs/Energy_Draw.md
docs/Monitoring.md
docs/_coverpage.md
docs/index.html
examples/Hyperparameter Optimization on Keras with Breast Cancer Data.ipynb
examples/Recover Best Models from Experiment Log.ipynb
setup.py
talos/__init__.py
talos/autom8/automodel.py
talos/callbacks/__init__.py
talos/callbacks/experiment_log.py
talos/callbacks/power_draw.py
talos/utils/__init__.py
tests/commands/test_latest.py
tests/commands/test_rest.py

Make callbacks to a submodule

---

.pep8speaks.yml

added pep8 config file

---

docs/Examples_Multiple_Inputs.md
docs/Examples_Typical_Code.md
docs/Predict.md
docs/Scan.md
docs/_coverpage.md
docs/index.html
examples/Hyperparameter Optimization on Keras with Breast Cancer Data.ipynb
setup.py
talos/__init__.py
talos/commands/evaluate.py
talos/commands/predict.py
talos/scan/Scan.py
talos/scan/scan_finish.py
talos/templates/models.py
talos/templates/params.py
talos/templates/pipelines.py
talos/utils/recover_best_model.py
talos/utils/validation_split.py
tests/commands/test_predict.py
tests/commands/test_random_methods.py

582 support multi input

---

docs/AutoParams.md
setup.py
talos/__init__.py

fixed old imports in docs
